name: Packaging

on: [push]

# push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install numpy
        run: python -m pip install numpy

      - run: bash swig/python-packaging/setup.sh
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/swig/python-packaging/
      - name: List
        run: pwd && ls build/swig/python-packaging

  build_wheels:
    needs: setup
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [macos-11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: List
        run: pwd && ls

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Use boost 1_72, since this allows c++11. We need c++11, since manylinux2014 only has gcc 4.8
          # Can't use boost 1.53 (default on linux) because it doesn't have rtree functionality
          CIBW_BUILD: cp36-manylinux_x86_64 cp36-win_amd64 cp36-macosx_x86_64
          CIBW_BEFORE_ALL_LINUX: >
              yum install -y lapack-devel gsl-devel armadillo-devel &&
              curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz &&
              tar -xf boost_1_72_0.tar.gz &&
              cd boost_1_72_0; cp -r boost /usr/include
          CIBW_BEFORE_ALL_MACOS: |
              # Other than the latest version, Brew only has boost 1.76. Therefore we must install boost from source
              brew reinstall gcc lapack gsl armadillo
              curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz
              tar -xf boost_1_72_0.tar.gz
              cd boost_1_72_0
              cp -r boost /usr/local/include
              ls /usr/local/bin/
              ls /usr/local/opt/armadillo
              ls /usr/local/opt
              ln -s /usr/local/bin/gcc-13 /usr/local/bin/gcc
              ln -s /usr/local/bin/g++-13 /usr/local/bin/g++
          CIBW_BEFORE_ALL_WINDOWS: choco install -y lapack-devel
          CIBW_TEST_COMMAND: >
              python -m pip install numpy &&
              python {project}/tests/check_installation.py
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl
